---
ip: "192.168.10.10"
memory: 2048
cpus: 1

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/[your-local-dev-base-path]/sites
      to: /home/vagrant/sites

#The repo var is only needed when cloning an existing project, for a new project leave this out.
sites:
    - name: example
      type: wordpress/laravel
      repo: https://github.com/username/repo.git
    - name: example2
      type: wordpress/laravel